name: First Bash

on: 
  push:
    branches:
      - "*"

jobs: #object : on, name, jobs...
  bash:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: run bash command
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - run: |
          echo $MY_SECRET

        