name: First Bash

on: 
  push:
    branches:
      - "*"

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run bash command
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo $MY_SECRET


        